[package]
name = "binding_tool"
version = "0.3.0"
edition = "2018"
authors = ["Daniel Mikusa <dmikusa@vmware.com>"]
description = "Generate Kubernetes service bindings for use with Cloud Native Buildpacks"

[dependencies]
anyhow = "1.0"

[dependencies.clap]
version = "2.33"
default-features = false

[dev_dependencies]
tempfile = "3"
